#!/usr/bin/env node
// build-pins.mjs — regenerate public/lab/pins.json (the Lens's gold pins)
// from yonder-site content frontmatter.
//
//   node scripts/build-pins.mjs
//
// Reads ../yonder-site/src/content/{projects,public-art}/*/index.md, keeps
// entries that have latitude/longitude, are published, and haven't opted out
// of the deep map (deep_map: false), and emits a GeoJSON FeatureCollection
// with enough properties for the Lens's specimen card: title, url (the wall's
// page on yonderartland.com), img (featured image, absolute), type, town,
// and year. New walls flow in with one run of this script.

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const YONDER = resolve(HERE, '../../yonder-site/src/content');
const OUT = resolve(HERE, '../public/lab/pins.json');
const SITE = 'https://www.yonderartland.com';

// [collection dir, url path prefix on yonderartland.com]
const COLLECTIONS = [
  ['projects', '/projects/'],
  ['public-art', '/public-art/'],
];

// Frontmatter here is flat single-line scalars for every key we need, so a
// line-based grab beats pulling in a YAML dependency.
const scalar = (fm, key) => {
  const m = fm.match(new RegExp(`^${key}:[ \\t]*(.+)$`, 'm'));
  if (!m) return undefined;
  return m[1].trim().replace(/^["']|["']$/g, '');
};

// "211 E Walnut St, Green Bay, WI 54301" -> "Green Bay"
const townFromAddress = (address) => {
  if (!address) return undefined;
  const m = address.match(/,\s*([^,]+),\s*WI\b/);
  return m ? m[1].trim() : undefined;
};

// First sentence of the description, capped for the specimen card.
const cardLine = (description) => {
  if (!description) return undefined;
  const first = description.match(/^.*?[.!?](?=\s|$)/)?.[0] ?? description;
  if (first.length <= 170) return first;
  return first.slice(0, 167).replace(/\s+\S*$/, '') + '…';
};

const features = [];
let skipped = 0;

for (const [dir, prefix] of COLLECTIONS) {
  const base = join(YONDER, dir);
  for (const entry of readdirSync(base)) {
    const file = join(base, entry, 'index.md');
    if (!existsSync(file)) continue;
    const src = readFileSync(file, 'utf8');
    const fmMatch = src.match(/^---\n([\s\S]*?)\n---/);
    if (!fmMatch) continue;
    const fm = fmMatch[1];

    const lat = parseFloat(scalar(fm, 'latitude'));
    const lng = parseFloat(scalar(fm, 'longitude'));
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;

    if (scalar(fm, 'status') === 'draft' || /^deep_map:\s*false/m.test(fm)) {
      skipped++;
      continue;
    }

    const slug = scalar(fm, 'slug') ?? entry;
    const img = scalar(fm, 'featured_image');
    const date = scalar(fm, 'date');
    const year = date ? parseInt(date.slice(0, 4), 10) : parseInt(scalar(fm, 'year'), 10);

    const properties = {
      title: scalar(fm, 'title'),
      url: `${SITE}${prefix}${slug}/`,
    };
    if (img) properties.img = img.startsWith('/') ? `${SITE}${img}` : img;
    const type = scalar(fm, 'type') ?? (dir === 'public-art' ? 'public art' : undefined);
    if (type) properties.type = type;
    const town = townFromAddress(scalar(fm, 'address'));
    if (town) properties.town = town;
    if (Number.isFinite(year)) properties.year = year;
    const desc = cardLine(scalar(fm, 'description'));
    if (desc) properties.desc = desc;

    features.push({
      type: 'Feature',
      properties,
      geometry: { type: 'Point', coordinates: [lng, lat] },
    });
  }
}

features.sort((a, b) => a.properties.url.localeCompare(b.properties.url));

const out = {
  _note:
    'Generated by scripts/build-pins.mjs from yonder-site content frontmatter — do not edit by hand. Regenerate: node scripts/build-pins.mjs',
  type: 'FeatureCollection',
  features,
};

writeFileSync(OUT, JSON.stringify(out) + '\n');
console.log(`pins.json: ${features.length} pins written (${skipped} skipped as draft/deep_map:false)`);
